### ISSUE TITLE
What servers can I use?

### ISSUE THREAD

**Issue by rzyyx** [michaljaz/webmc#107]
I want to test out PvP on this Minecraft Web client, but I just cant find any servers, I tried a bunch of cracked servers, and it didnt work, I tried premium servers, didn't work.

**Comment by TechNinja-js** [comment]
> It should work on 1.16.5 with offline mode (for example paper)

What do you mean by this?

**Comment by dragonismcode** [comment]
> > It should work on 1.16.5 with offline mode (for example paper)
> 
> What do you mean by this?

In the server.properties file, there is a property called "online-mode", if you turn this off, this is called offline mode (also known as cracked servers). For WebMC to connect to a server since it allows players to have their own nickname, the server needs to be cracked.

Does this answer your question?
